version: '3.4'

services:
  mysql:
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
      MYSQL_DATABASE: university-book-shop

      # - MYSQL_DATABASE=university-book-shop
      # - MYSQL_ROOT_PASSWORD=root
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=root
    ports:
      - 33062:3306
    volumes:
      - ./mysql-data:/var/lib/mysql

  universitybookshop.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DbConnection= Server=mysql_8_0_36; Database=university-book-shop; Port= 3306; User Id = root; Password=root; 
    ports:
      - "7265:80"
      - "7266:443"
    restart: always
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  reactApp:
    environment:
      - WDS_SOCKET_PORT= 0
    ports:
      - "5001:3000"

  proxy:
    restart: always
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

volumes:
  mysql-data:
