version: '3.4'

services:
  # mysql:
  #   image: mysql:8.0.36
  #   container_name: mysql_8_0_36

  # universitybookshop.api:
  #   image: universitybookshopapi
  #   build:
  #     context: .
  #     dockerfile: src/dotnet-app/UniversityBookShop.Api/Dockerfile
  #   depends_on:
  #     - mysql

  # reactApp:
  #   image: react-app
  #   build:
  #     context: ./src/react-app/university-book-shop/
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - universitybookshop.api

  # proxy:
  #   image: nginx:mainline
  #   depends_on:
  #     - reactApp

  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: docker-ms-sql-server

  identity.api:
    image: identityapi
    build:
      context: .
      dockerfile: src/dotnet-app/Identity.Api/Dockerfile
    depends_on:
      - mssql

  identityserver.api:
    image: identityserverapi
    build:
      context: .
      dockerfile: src/dotnet-app/IdentityServer.Api/Dockerfile
    depends_on:
      - mssql

