using UniversityBookShop.Domain.Entities;

namespace UniversityBookShop.Persistence.InitialData
{
    internal static class FacultyInitialData
    {
        public static List<Faculty> GetInitialData()
        {
            return new List<Faculty>
            {
                new Faculty() { Id = 1, Name = "Faculty of Science", UniversityId = 1 },
                new Faculty() { Id = 2, Name = "School of Engineering", UniversityId = 1 },
                new Faculty() { Id = 3, Name = "College of Arts and Humanities", UniversityId = 1 },
                new Faculty() { Id = 4, Name = "Business and Economics Department", UniversityId = 1 },
                new Faculty() { Id = 5, Name = "Medical School", UniversityId = 1 },
                new Faculty() { Id = 6, Name = "Astronomy and Astrophysics Department", UniversityId = 1 },
                new Faculty() { Id = 7, Name = "Environmental Studies Division", UniversityId = 1 },
                new Faculty() { Id = 8, Name = "Law and Legal Studies", UniversityId = 1 },
                new Faculty() { Id = 9, Name = "Social Sciences Institute", UniversityId = 1 },
                new Faculty() { Id = 10, Name = "School of Computing", UniversityId = 1 },
                new Faculty() { Id = 11, Name = "Music and Performing Arts Department", UniversityId = 1 },
                new Faculty() { Id = 12, Name = "Quantum Computing Research Division", UniversityId = 1 },
                new Faculty() { Id = 13, Name = "Computer Science and Engineering", UniversityId = 2 },
                new Faculty() { Id = 14, Name = "Mechanical Engineering Department", UniversityId = 2 },
                new Faculty() { Id = 15, Name = "Electrical and Electronics Division", UniversityId = 2 },
                new Faculty() { Id = 16, Name = "Biotechnology and Life Sciences", UniversityId = 2 },
                new Faculty() { Id = 17, Name = "Business Analytics and Economics", UniversityId = 2 },
                new Faculty() { Id = 18, Name = "Robotics and Automation Institute", UniversityId = 2 },
                new Faculty() { Id = 19, Name = "Cybersecurity Research Center", UniversityId = 2 },
                new Faculty() { Id = 20, Name = "Aviation and Aerospace Studies", UniversityId = 2 },
                new Faculty() { Id = 21, Name = "Virtual Reality and Gaming Department", UniversityId = 2 },
                new Faculty() { Id = 22, Name = "Applied Physics and Mathematics", UniversityId = 2 },
                new Faculty() { Id = 23, Name = "Industrial Design and Innovation", UniversityId = 2 },
                new Faculty() { Id = 24, Name = "Space Exploration Division", UniversityId = 2 },
                new Faculty() { Id = 25, Name = "Fine Arts and Sculpture", UniversityId = 3 },
                new Faculty() { Id = 26, Name = "Drama and Performing Arts", UniversityId = 3 },
                new Faculty() { Id = 27, Name = "Creative Writing and Literature", UniversityId = 3 },
                new Faculty() { Id = 28, Name = "Music Composition and Performance", UniversityId = 3 },
                new Faculty() { Id = 29, Name = "Digital Media and Design", UniversityId = 3 },
                new Faculty() { Id = 30, Name = "Fashion Design and Textiles", UniversityId = 3 },
                new Faculty() { Id = 31, Name = "Photography and Visual Arts", UniversityId = 3 },
                new Faculty() { Id = 32, Name = "Culinary Arts and Gastronomy", UniversityId = 3 },
                new Faculty() { Id = 33, Name = "Film Production and Cinematography", UniversityId = 3 },
                new Faculty() { Id = 34, Name = "Animation and Multimedia Studies", UniversityId = 3 },
                new Faculty() { Id = 35, Name = "Art History and Criticism", UniversityId = 3 },
                new Faculty() { Id = 36, Name = "Cultural Studies and Anthropology", UniversityId = 3 },
                new Faculty() { Id = 37, Name = "Finance and Investment", UniversityId = 4 },
                new Faculty() { Id = 38, Name = "Marketing and Sales", UniversityId = 4 },
                new Faculty() { Id = 39, Name = "Management and Leadership", UniversityId = 4 },
                new Faculty() { Id = 40, Name = "Entrepreneurship and Innovation", UniversityId = 4 },
                new Faculty() { Id = 41, Name = "Business Analytics and Strategy", UniversityId = 4 },
                new Faculty() { Id = 42, Name = "Supply Chain and Logistics", UniversityId = 4 },
                new Faculty() { Id = 43, Name = "Human Resources and Organizational Behavior", UniversityId = 4 },
                new Faculty() { Id = 44, Name = "International Business Studies", UniversityId = 4 },
                new Faculty() { Id = 45, Name = "Economics and Global Markets", UniversityId = 4 },
                new Faculty() { Id = 46, Name = "Corporate Governance and Ethics", UniversityId = 4 },
                new Faculty() { Id = 47, Name = "Real Estate and Property Management", UniversityId = 4 },
                new Faculty() { Id = 48, Name = "Hospitality and Tourism Management", UniversityId = 4 },
                new Faculty() { Id = 49, Name = "Medicine and Surgery", UniversityId = 5 },
                new Faculty() { Id = 50, Name = "Nursing and Healthcare Management", UniversityId = 5 },
                new Faculty() { Id = 51, Name = "Pharmacy and Pharmaceutical Sciences", UniversityId = 5 },
                new Faculty() { Id = 52, Name = "Dentistry and Oral Health", UniversityId = 5 },
                new Faculty() { Id = 53, Name = "Medical Research and Biotechnology", UniversityId = 5 },
                new Faculty() { Id = 54, Name = "Public Health and Epidemiology", UniversityId = 5 },
                new Faculty() { Id = 55, Name = "Nutrition and Dietetics", UniversityId = 5 },
                new Faculty() { Id = 56, Name = "Psychology and Mental Health Studies", UniversityId = 5 },
                new Faculty() { Id = 57, Name = "Rehabilitation Sciences", UniversityId = 5 },
                new Faculty() { Id = 58, Name = "Veterinary Medicine", UniversityId = 5 },
                new Faculty() { Id = 59, Name = "Medical Ethics and Legal Studies", UniversityId = 5 },
                new Faculty() { Id = 60, Name = "Alternative and Complementary Medicine", UniversityId = 5 },
                new Faculty() { Id = 61, Name = "Astrology and Horoscopes", UniversityId = 6 },
                new Faculty() { Id = 62, Name = "Celestial Mathematics", UniversityId = 6 },
                new Faculty() { Id = 63, Name = "Planetary Physics", UniversityId = 6 },
                new Faculty() { Id = 64, Name = "Mystical Astronomy", UniversityId = 6 },
                new Faculty() { Id = 65, Name = "Astrological Data Science", UniversityId = 6 },
                new Faculty() { Id = 66, Name = "Astrobiology and Extraterrestrial Life", UniversityId = 6 },
                new Faculty() { Id = 67, Name = "Cosmic Phenomena Studies", UniversityId = 6 },
                new Faculty() { Id = 68, Name = "Astrological Arts and Culture", UniversityId = 6 },
                new Faculty() { Id = 69, Name = "Zodiacal Psychology", UniversityId = 6 },
                new Faculty() { Id = 70, Name = "Astrological Predictive Modeling", UniversityId = 6 },
                new Faculty() { Id = 71, Name = "Stellar Cartography", UniversityId = 6 },
                new Faculty() { Id = 72, Name = "Quantum Astrology Research", UniversityId = 6 },
                new Faculty() { Id = 73, Name = "Ecology and Biodiversity", UniversityId = 7 },
                new Faculty() { Id = 74, Name = "Environmental Policy and Governance", UniversityId = 7 },
                new Faculty() { Id = 75, Name = "Renewable Energy and Sustainability", UniversityId = 7 },
                new Faculty() { Id = 76, Name = "Climate Change and Adaptation", UniversityId = 7 },
                new Faculty() { Id = 77, Name = "Marine Biology and Oceanography", UniversityId = 7 },
                new Faculty() { Id = 78, Name = "Environmental Chemistry and Toxicology", UniversityId = 7 },
                new Faculty() { Id = 79, Name = "Green Architecture and Urban Planning", UniversityId = 7 },
                new Faculty() { Id = 80, Name = "Wildlife Conservation and Management", UniversityId = 7 },
                new Faculty() { Id = 81, Name = "Environmental Engineering", UniversityId = 7 },
                new Faculty() { Id = 82, Name = "Sustainable Agriculture and Food Systems", UniversityId = 7 },
                new Faculty() { Id = 83, Name = "Ecotourism and Nature-Based Recreation", UniversityId = 7 },
                new Faculty() { Id = 84, Name = "Environmental Ethics and Philosophy", UniversityId = 7 },
                new Faculty() { Id = 85, Name = "International Law and Diplomacy", UniversityId = 8 },
                new Faculty() { Id = 86, Name = "Criminal Law and Justice", UniversityId = 8 },
                new Faculty() { Id = 87, Name = "Corporate and Business Law", UniversityId = 8 },
                new Faculty() { Id = 88, Name = "Human Rights and Social Justice", UniversityId = 8 },
                new Faculty() { Id = 89, Name = "Environmental Law and Sustainability", UniversityId = 8 },
                new Faculty() { Id = 90, Name = "Intellectual Property and Technology Law", UniversityId = 8 },
                new Faculty() { Id = 91, Name = "Health Law and Bioethics", UniversityId = 8 },
                new Faculty() { Id = 92, Name = "Legal Studies and Ethics", UniversityId = 8 },
                new Faculty() { Id = 93, Name = "Family and Juvenile Law", UniversityId = 8 },
                new Faculty() { Id = 94, Name = "International Humanitarian Law", UniversityId = 8 },
                new Faculty() { Id = 95, Name = "Alternative Dispute Resolution", UniversityId = 8 },
                new Faculty() { Id = 96, Name = "Space Law and Policy", UniversityId = 8 },
                new Faculty() { Id = 97, Name = "Quantum Algorithms and Complexity", UniversityId = 12 },
                new Faculty() { Id = 98, Name = "Quantum Machine Learning", UniversityId = 12 },
                new Faculty() { Id = 99, Name = "Quantum Cryptography", UniversityId = 12 },
                new Faculty() { Id = 100, Name = "Quantum Information and Entanglement", UniversityId = 12 },
                new Faculty() { Id = 101, Name = "Quantum Hardware Development", UniversityId = 12 },
                new Faculty() { Id = 102, Name = "Quantum Software Engineering", UniversityId = 12 },
                new Faculty() { Id = 103, Name = "Quantum Networking", UniversityId = 12 },
                new Faculty() { Id = 104, Name = "Quantum Artificial Intelligence", UniversityId = 12 },
                new Faculty() { Id = 105, Name = "Quantum Simulation", UniversityId = 12 },
                new Faculty() { Id = 106, Name = "Quantum Error Correction", UniversityId = 12 },
                new Faculty() { Id = 107, Name = "Quantum Ethics and Philosophy", UniversityId = 12 },
                new Faculty() { Id = 108, Name = "Quantum Computing and Astrophysics", UniversityId = 12 },
                new Faculty() { Id = 109, Name = "Observational Astronomy", UniversityId = 9 },
                new Faculty() { Id = 110, Name = "Theoretical Astrophysics", UniversityId = 9 },
                new Faculty() { Id = 111, Name = "Planetary Science and Geophysics", UniversityId = 9 },
                new Faculty() { Id = 112, Name = "Astrochemistry and Astrobiology", UniversityId = 9 },
                new Faculty() { Id = 113, Name = "Galactic Dynamics and Cosmology", UniversityId = 9 },
                new Faculty() { Id = 114, Name = "Astroinformatics and Data Science", UniversityId = 9 },
                new Faculty() { Id = 115, Name = "Exoplanetary Studies", UniversityId = 9 },
                new Faculty() { Id = 116, Name = "Space Mission Planning and Engineering", UniversityId = 9 },
                new Faculty() { Id = 117, Name = "Astrophysical Instrumentation", UniversityId = 9 },
                new Faculty() { Id = 118, Name = "Astrosociology and Cultural Astronomy", UniversityId = 9 },
                new Faculty() { Id = 119, Name = "Radio Astronomy and Signal Processing", UniversityId = 9 },
                new Faculty() { Id = 120, Name = "Dark Matter and Dark Energy Research", UniversityId = 9 },
                new Faculty() { Id = 121, Name = "Interstellar Relations", UniversityId = 10 },
                new Faculty() { Id = 122, Name = "Intergalactic Sociology", UniversityId = 10 },
                new Faculty() { Id = 123, Name = "Astropolitical Science", UniversityId = 10 },
                new Faculty() { Id = 124, Name = "Planetary Economics", UniversityId = 10 },
                new Faculty() { Id = 125, Name = "Space Anthropology", UniversityId = 10 },
                new Faculty() { Id = 126, Name = "Astrosociology and Extraterrestrial Cultures", UniversityId = 10 },
                new Faculty() { Id = 127, Name = "Planetary Governance and Policy Studies", UniversityId = 10 },
                new Faculty() { Id = 128, Name = "Space Psychology", UniversityId = 10 },
                new Faculty() { Id = 129, Name = "Astroethics and Intergalactic Morality", UniversityId = 10 },
                new Faculty() { Id = 130, Name = "Exosociology and Alien Civilizations", UniversityId = 10 },
                new Faculty() { Id = 131, Name = "Astrohistory and Futurology", UniversityId = 10 },
                new Faculty() { Id = 132, Name = "Interplanetary Communication Studies", UniversityId = 10 },
                new Faculty() { Id = 133, Name = "Quantum Algorithms and Complexity", UniversityId = 11 },
                new Faculty() { Id = 134, Name = "Quantum Machine Learning", UniversityId = 11 },
                new Faculty() { Id = 135, Name = "Quantum Cryptography", UniversityId = 11 },
                new Faculty() { Id = 136, Name = "Quantum Information and Entanglement", UniversityId = 11 },
                new Faculty() { Id = 137, Name = "Quantum Hardware Development", UniversityId = 11 },
                new Faculty() { Id = 138, Name = "Quantum Software Engineering", UniversityId = 11 },
                new Faculty() { Id = 139, Name = "Quantum Networking", UniversityId = 11 },
                new Faculty() { Id = 140, Name = "Quantum Artificial Intelligence", UniversityId = 11 },
                new Faculty() { Id = 141, Name = "Quantum Simulation", UniversityId = 11 },
                new Faculty() { Id = 142, Name = "Quantum Error Correction", UniversityId = 11 },
                new Faculty() { Id = 143, Name = "Quantum Ethics and Philosophy", UniversityId = 11 },
                new Faculty() { Id = 144, Name = "Quantum Computing and Astrophysics", UniversityId = 11 },
            };
        }
    }
}
