// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversityBookShop.Persistence;

#nullable disable

namespace UniversityBookShop.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240312133211_InitialUniversityAndFacultyData")]
    partial class InitialUniversityAndFacultyData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UniversityBookShop.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("CurrencyCodesId")
                        .HasColumnType("int")
                        .HasColumnName("currency_code_id");

                    b.Property<string>("Isbn")
                        .HasMaxLength(17)
                        .HasColumnType("varchar(17)");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCodesId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Alice Starlight",
                            CurrencyCodesId = 1,
                            Isbn = "123456789012",
                            Name = "The Hidden Galaxy",
                            Price = 10m
                        },
                        new
                        {
                            Id = 2,
                            Author = "David Nebula",
                            CurrencyCodesId = 1,
                            Isbn = "234567890123",
                            Name = "Echoes of Eternity",
                            Price = 15m
                        },
                        new
                        {
                            Id = 3,
                            Author = "Mia Moonshade",
                            CurrencyCodesId = 1,
                            Isbn = "345678901234",
                            Name = "Serenade of Shadows",
                            Price = 20m
                        },
                        new
                        {
                            Id = 4,
                            Author = "Elijah Stardust",
                            CurrencyCodesId = 1,
                            Isbn = "456789012345",
                            Name = "Whispers in the Wind",
                            Price = 25m
                        },
                        new
                        {
                            Id = 5,
                            Author = "Isabella Dreamweaver",
                            CurrencyCodesId = 1,
                            Isbn = "567890123456",
                            Name = "The Enchanted Chronicles",
                            Price = 30m
                        },
                        new
                        {
                            Id = 6,
                            Author = "Oliver Starcrafter",
                            CurrencyCodesId = 1,
                            Isbn = "678901234567",
                            Name = "Chronicles of Arcadia",
                            Price = 35m
                        },
                        new
                        {
                            Id = 7,
                            Author = "Sophia Silverleaf",
                            CurrencyCodesId = 1,
                            Isbn = "789012345678",
                            Name = "Legends of Lumina",
                            Price = 40m
                        },
                        new
                        {
                            Id = 8,
                            Author = "Gabriel Nightshade",
                            CurrencyCodesId = 1,
                            Isbn = "890123456789",
                            Name = "Eternal Echoes",
                            Price = 45m
                        },
                        new
                        {
                            Id = 9,
                            Author = "Aria Stardancer",
                            CurrencyCodesId = 1,
                            Isbn = "901234567890",
                            Name = "Starlight Sonata",
                            Price = 50m
                        },
                        new
                        {
                            Id = 10,
                            Author = "Liam Shadowcaster",
                            CurrencyCodesId = 1,
                            Isbn = "012345678901",
                            Name = "Moonlit Whispers",
                            Price = 55m
                        },
                        new
                        {
                            Id = 11,
                            Author = "Serena Dreamweaver",
                            CurrencyCodesId = 1,
                            Isbn = "112233445566",
                            Name = "Wonders of Whimsy",
                            Price = 60m
                        },
                        new
                        {
                            Id = 12,
                            Author = "Lucas Starborn",
                            CurrencyCodesId = 1,
                            Isbn = "223344556677",
                            Name = "Stardust Serenade",
                            Price = 65m
                        },
                        new
                        {
                            Id = 13,
                            Author = "Aurora Celestia",
                            CurrencyCodesId = 1,
                            Isbn = "334455667788",
                            Name = "Realm of Radiance",
                            Price = 70m
                        },
                        new
                        {
                            Id = 14,
                            Author = "Xander Nightshade",
                            CurrencyCodesId = 1,
                            Isbn = "445566778899",
                            Name = "Midnight Mirage",
                            Price = 75m
                        },
                        new
                        {
                            Id = 15,
                            Author = "Fiona Starlight",
                            CurrencyCodesId = 1,
                            Isbn = "556677889900",
                            Name = "Twilight Tales",
                            Price = 80m
                        },
                        new
                        {
                            Id = 16,
                            Author = "Zane Moonshadow",
                            CurrencyCodesId = 1,
                            Isbn = "667788990011",
                            Name = "Cerulean Chronicles",
                            Price = 85m
                        },
                        new
                        {
                            Id = 17,
                            Author = "Elena Stardust",
                            CurrencyCodesId = 1,
                            Isbn = "778899001122",
                            Name = "Luminous Legends",
                            Price = 90m
                        },
                        new
                        {
                            Id = 18,
                            Author = "Orion Starcrafter",
                            CurrencyCodesId = 1,
                            Isbn = "889900112233",
                            Name = "Galactic Gala",
                            Price = 95m
                        });
                });

            modelBuilder.Entity("UniversityBookShop.Domain.Entities.BooksAvailableForFaculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsPurchased")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("UniversityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("UniversityId");

                    b.ToTable("books_available_for_faculty", (string)null);
                });

            modelBuilder.Entity("UniversityBookShop.Domain.Entities.CurrencyCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.HasKey("Id");

                    b.ToTable("currency_codes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "$"
                        },
                        new
                        {
                            Id = 2,
                            Code = "€"
                        });
                });

            modelBuilder.Entity("UniversityBookShop.Domain.Entities.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<int?>("UniversityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Faculty of Science",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "School of Engineering",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "College of Arts and Humanities",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Business and Economics Department",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Medical School",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Astronomy and Astrophysics Department",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Environmental Studies Division",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Law and Legal Studies",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Social Sciences Institute",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "School of Computing",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Music and Performing Arts Department",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Quantum Computing Research Division",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 13,
                            Name = "Computer Science and Engineering",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 14,
                            Name = "Mechanical Engineering Department",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 15,
                            Name = "Electrical and Electronics Division",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 16,
                            Name = "Biotechnology and Life Sciences",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 17,
                            Name = "Business Analytics and Economics",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 18,
                            Name = "Robotics and Automation Institute",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 19,
                            Name = "Cybersecurity Research Center",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 20,
                            Name = "Aviation and Aerospace Studies",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 21,
                            Name = "Virtual Reality and Gaming Department",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 22,
                            Name = "Applied Physics and Mathematics",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 23,
                            Name = "Industrial Design and Innovation",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 24,
                            Name = "Space Exploration Division",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 25,
                            Name = "Fine Arts and Sculpture",
                            UniversityId = 3
                        },
                        new
                        {
                            Id = 26,
                            Name = "Drama and Performing Arts",
                            UniversityId = 3
                        },
                        new
                        {
                            Id = 27,
                            Name = "Creative Writing and Literature",
                            UniversityId = 3
                        },
                        new
                        {
                            Id = 28,
                            Name = "Music Composition and Performance",
                            UniversityId = 3
                        },
                        new
                        {
                            Id = 29,
                            Name = "Digital Media and Design",
                            UniversityId = 3
                        },
                        new
                        {
                            Id = 30,
                            Name = "Fashion Design and Textiles",
                            UniversityId = 3
                        },
                        new
                        {
                            Id = 31,
                            Name = "Photography and Visual Arts",
                            UniversityId = 3
                        },
                        new
                        {
                            Id = 32,
                            Name = "Culinary Arts and Gastronomy",
                            UniversityId = 3
                        },
                        new
                        {
                            Id = 33,
                            Name = "Film Production and Cinematography",
                            UniversityId = 3
                        },
                        new
                        {
                            Id = 34,
                            Name = "Animation and Multimedia Studies",
                            UniversityId = 3
                        },
                        new
                        {
                            Id = 35,
                            Name = "Art History and Criticism",
                            UniversityId = 3
                        },
                        new
                        {
                            Id = 36,
                            Name = "Cultural Studies and Anthropology",
                            UniversityId = 3
                        },
                        new
                        {
                            Id = 37,
                            Name = "Finance and Investment",
                            UniversityId = 4
                        },
                        new
                        {
                            Id = 38,
                            Name = "Marketing and Sales",
                            UniversityId = 4
                        },
                        new
                        {
                            Id = 39,
                            Name = "Management and Leadership",
                            UniversityId = 4
                        },
                        new
                        {
                            Id = 40,
                            Name = "Entrepreneurship and Innovation",
                            UniversityId = 4
                        },
                        new
                        {
                            Id = 41,
                            Name = "Business Analytics and Strategy",
                            UniversityId = 4
                        },
                        new
                        {
                            Id = 42,
                            Name = "Supply Chain and Logistics",
                            UniversityId = 4
                        },
                        new
                        {
                            Id = 43,
                            Name = "Human Resources and Organizational Behavior",
                            UniversityId = 4
                        },
                        new
                        {
                            Id = 44,
                            Name = "International Business Studies",
                            UniversityId = 4
                        },
                        new
                        {
                            Id = 45,
                            Name = "Economics and Global Markets",
                            UniversityId = 4
                        },
                        new
                        {
                            Id = 46,
                            Name = "Corporate Governance and Ethics",
                            UniversityId = 4
                        },
                        new
                        {
                            Id = 47,
                            Name = "Real Estate and Property Management",
                            UniversityId = 4
                        },
                        new
                        {
                            Id = 48,
                            Name = "Hospitality and Tourism Management",
                            UniversityId = 4
                        },
                        new
                        {
                            Id = 49,
                            Name = "Medicine and Surgery",
                            UniversityId = 5
                        },
                        new
                        {
                            Id = 50,
                            Name = "Nursing and Healthcare Management",
                            UniversityId = 5
                        },
                        new
                        {
                            Id = 51,
                            Name = "Pharmacy and Pharmaceutical Sciences",
                            UniversityId = 5
                        },
                        new
                        {
                            Id = 52,
                            Name = "Dentistry and Oral Health",
                            UniversityId = 5
                        },
                        new
                        {
                            Id = 53,
                            Name = "Medical Research and Biotechnology",
                            UniversityId = 5
                        },
                        new
                        {
                            Id = 54,
                            Name = "Public Health and Epidemiology",
                            UniversityId = 5
                        },
                        new
                        {
                            Id = 55,
                            Name = "Nutrition and Dietetics",
                            UniversityId = 5
                        },
                        new
                        {
                            Id = 56,
                            Name = "Psychology and Mental Health Studies",
                            UniversityId = 5
                        },
                        new
                        {
                            Id = 57,
                            Name = "Rehabilitation Sciences",
                            UniversityId = 5
                        },
                        new
                        {
                            Id = 58,
                            Name = "Veterinary Medicine",
                            UniversityId = 5
                        },
                        new
                        {
                            Id = 59,
                            Name = "Medical Ethics and Legal Studies",
                            UniversityId = 5
                        },
                        new
                        {
                            Id = 60,
                            Name = "Alternative and Complementary Medicine",
                            UniversityId = 5
                        },
                        new
                        {
                            Id = 61,
                            Name = "Astrology and Horoscopes",
                            UniversityId = 6
                        },
                        new
                        {
                            Id = 62,
                            Name = "Celestial Mathematics",
                            UniversityId = 6
                        },
                        new
                        {
                            Id = 63,
                            Name = "Planetary Physics",
                            UniversityId = 6
                        },
                        new
                        {
                            Id = 64,
                            Name = "Mystical Astronomy",
                            UniversityId = 6
                        },
                        new
                        {
                            Id = 65,
                            Name = "Astrological Data Science",
                            UniversityId = 6
                        },
                        new
                        {
                            Id = 66,
                            Name = "Astrobiology and Extraterrestrial Life",
                            UniversityId = 6
                        },
                        new
                        {
                            Id = 67,
                            Name = "Cosmic Phenomena Studies",
                            UniversityId = 6
                        },
                        new
                        {
                            Id = 68,
                            Name = "Astrological Arts and Culture",
                            UniversityId = 6
                        },
                        new
                        {
                            Id = 69,
                            Name = "Zodiacal Psychology",
                            UniversityId = 6
                        },
                        new
                        {
                            Id = 70,
                            Name = "Astrological Predictive Modeling",
                            UniversityId = 6
                        },
                        new
                        {
                            Id = 71,
                            Name = "Stellar Cartography",
                            UniversityId = 6
                        },
                        new
                        {
                            Id = 72,
                            Name = "Quantum Astrology Research",
                            UniversityId = 6
                        },
                        new
                        {
                            Id = 73,
                            Name = "Ecology and Biodiversity",
                            UniversityId = 7
                        },
                        new
                        {
                            Id = 74,
                            Name = "Environmental Policy and Governance",
                            UniversityId = 7
                        },
                        new
                        {
                            Id = 75,
                            Name = "Renewable Energy and Sustainability",
                            UniversityId = 7
                        },
                        new
                        {
                            Id = 76,
                            Name = "Climate Change and Adaptation",
                            UniversityId = 7
                        },
                        new
                        {
                            Id = 77,
                            Name = "Marine Biology and Oceanography",
                            UniversityId = 7
                        },
                        new
                        {
                            Id = 78,
                            Name = "Environmental Chemistry and Toxicology",
                            UniversityId = 7
                        },
                        new
                        {
                            Id = 79,
                            Name = "Green Architecture and Urban Planning",
                            UniversityId = 7
                        },
                        new
                        {
                            Id = 80,
                            Name = "Wildlife Conservation and Management",
                            UniversityId = 7
                        },
                        new
                        {
                            Id = 81,
                            Name = "Environmental Engineering",
                            UniversityId = 7
                        },
                        new
                        {
                            Id = 82,
                            Name = "Sustainable Agriculture and Food Systems",
                            UniversityId = 7
                        },
                        new
                        {
                            Id = 83,
                            Name = "Ecotourism and Nature-Based Recreation",
                            UniversityId = 7
                        },
                        new
                        {
                            Id = 84,
                            Name = "Environmental Ethics and Philosophy",
                            UniversityId = 7
                        },
                        new
                        {
                            Id = 85,
                            Name = "International Law and Diplomacy",
                            UniversityId = 8
                        },
                        new
                        {
                            Id = 86,
                            Name = "Criminal Law and Justice",
                            UniversityId = 8
                        },
                        new
                        {
                            Id = 87,
                            Name = "Corporate and Business Law",
                            UniversityId = 8
                        },
                        new
                        {
                            Id = 88,
                            Name = "Human Rights and Social Justice",
                            UniversityId = 8
                        },
                        new
                        {
                            Id = 89,
                            Name = "Environmental Law and Sustainability",
                            UniversityId = 8
                        },
                        new
                        {
                            Id = 90,
                            Name = "Intellectual Property and Technology Law",
                            UniversityId = 8
                        },
                        new
                        {
                            Id = 91,
                            Name = "Health Law and Bioethics",
                            UniversityId = 8
                        },
                        new
                        {
                            Id = 92,
                            Name = "Legal Studies and Ethics",
                            UniversityId = 8
                        },
                        new
                        {
                            Id = 93,
                            Name = "Family and Juvenile Law",
                            UniversityId = 8
                        },
                        new
                        {
                            Id = 94,
                            Name = "International Humanitarian Law",
                            UniversityId = 8
                        },
                        new
                        {
                            Id = 95,
                            Name = "Alternative Dispute Resolution",
                            UniversityId = 8
                        },
                        new
                        {
                            Id = 96,
                            Name = "Space Law and Policy",
                            UniversityId = 8
                        },
                        new
                        {
                            Id = 97,
                            Name = "Quantum Algorithms and Complexity",
                            UniversityId = 12
                        },
                        new
                        {
                            Id = 98,
                            Name = "Quantum Machine Learning",
                            UniversityId = 12
                        },
                        new
                        {
                            Id = 99,
                            Name = "Quantum Cryptography",
                            UniversityId = 12
                        },
                        new
                        {
                            Id = 100,
                            Name = "Quantum Information and Entanglement",
                            UniversityId = 12
                        },
                        new
                        {
                            Id = 101,
                            Name = "Quantum Hardware Development",
                            UniversityId = 12
                        },
                        new
                        {
                            Id = 102,
                            Name = "Quantum Software Engineering",
                            UniversityId = 12
                        },
                        new
                        {
                            Id = 103,
                            Name = "Quantum Networking",
                            UniversityId = 12
                        },
                        new
                        {
                            Id = 104,
                            Name = "Quantum Artificial Intelligence",
                            UniversityId = 12
                        },
                        new
                        {
                            Id = 105,
                            Name = "Quantum Simulation",
                            UniversityId = 12
                        },
                        new
                        {
                            Id = 106,
                            Name = "Quantum Error Correction",
                            UniversityId = 12
                        },
                        new
                        {
                            Id = 107,
                            Name = "Quantum Ethics and Philosophy",
                            UniversityId = 12
                        },
                        new
                        {
                            Id = 108,
                            Name = "Quantum Computing and Astrophysics",
                            UniversityId = 12
                        },
                        new
                        {
                            Id = 109,
                            Name = "Observational Astronomy",
                            UniversityId = 9
                        },
                        new
                        {
                            Id = 110,
                            Name = "Theoretical Astrophysics",
                            UniversityId = 9
                        },
                        new
                        {
                            Id = 111,
                            Name = "Planetary Science and Geophysics",
                            UniversityId = 9
                        },
                        new
                        {
                            Id = 112,
                            Name = "Astrochemistry and Astrobiology",
                            UniversityId = 9
                        },
                        new
                        {
                            Id = 113,
                            Name = "Galactic Dynamics and Cosmology",
                            UniversityId = 9
                        },
                        new
                        {
                            Id = 114,
                            Name = "Astroinformatics and Data Science",
                            UniversityId = 9
                        },
                        new
                        {
                            Id = 115,
                            Name = "Exoplanetary Studies",
                            UniversityId = 9
                        },
                        new
                        {
                            Id = 116,
                            Name = "Space Mission Planning and Engineering",
                            UniversityId = 9
                        },
                        new
                        {
                            Id = 117,
                            Name = "Astrophysical Instrumentation",
                            UniversityId = 9
                        },
                        new
                        {
                            Id = 118,
                            Name = "Astrosociology and Cultural Astronomy",
                            UniversityId = 9
                        },
                        new
                        {
                            Id = 119,
                            Name = "Radio Astronomy and Signal Processing",
                            UniversityId = 9
                        },
                        new
                        {
                            Id = 120,
                            Name = "Dark Matter and Dark Energy Research",
                            UniversityId = 9
                        },
                        new
                        {
                            Id = 121,
                            Name = "Interstellar Relations",
                            UniversityId = 10
                        },
                        new
                        {
                            Id = 122,
                            Name = "Intergalactic Sociology",
                            UniversityId = 10
                        },
                        new
                        {
                            Id = 123,
                            Name = "Astropolitical Science",
                            UniversityId = 10
                        },
                        new
                        {
                            Id = 124,
                            Name = "Planetary Economics",
                            UniversityId = 10
                        },
                        new
                        {
                            Id = 125,
                            Name = "Space Anthropology",
                            UniversityId = 10
                        },
                        new
                        {
                            Id = 126,
                            Name = "Astrosociology and Extraterrestrial Cultures",
                            UniversityId = 10
                        },
                        new
                        {
                            Id = 127,
                            Name = "Planetary Governance and Policy Studies",
                            UniversityId = 10
                        },
                        new
                        {
                            Id = 128,
                            Name = "Space Psychology",
                            UniversityId = 10
                        },
                        new
                        {
                            Id = 129,
                            Name = "Astroethics and Intergalactic Morality",
                            UniversityId = 10
                        },
                        new
                        {
                            Id = 130,
                            Name = "Exosociology and Alien Civilizations",
                            UniversityId = 10
                        },
                        new
                        {
                            Id = 131,
                            Name = "Astrohistory and Futurology",
                            UniversityId = 10
                        },
                        new
                        {
                            Id = 132,
                            Name = "Interplanetary Communication Studies",
                            UniversityId = 10
                        },
                        new
                        {
                            Id = 133,
                            Name = "Quantum Algorithms and Complexity",
                            UniversityId = 11
                        },
                        new
                        {
                            Id = 134,
                            Name = "Quantum Machine Learning",
                            UniversityId = 11
                        },
                        new
                        {
                            Id = 135,
                            Name = "Quantum Cryptography",
                            UniversityId = 11
                        },
                        new
                        {
                            Id = 136,
                            Name = "Quantum Information and Entanglement",
                            UniversityId = 11
                        },
                        new
                        {
                            Id = 137,
                            Name = "Quantum Hardware Development",
                            UniversityId = 11
                        },
                        new
                        {
                            Id = 138,
                            Name = "Quantum Software Engineering",
                            UniversityId = 11
                        },
                        new
                        {
                            Id = 139,
                            Name = "Quantum Networking",
                            UniversityId = 11
                        },
                        new
                        {
                            Id = 140,
                            Name = "Quantum Artificial Intelligence",
                            UniversityId = 11
                        },
                        new
                        {
                            Id = 141,
                            Name = "Quantum Simulation",
                            UniversityId = 11
                        },
                        new
                        {
                            Id = 142,
                            Name = "Quantum Error Correction",
                            UniversityId = 11
                        },
                        new
                        {
                            Id = 143,
                            Name = "Quantum Ethics and Philosophy",
                            UniversityId = 11
                        },
                        new
                        {
                            Id = 144,
                            Name = "Quantum Computing and Astrophysics",
                            UniversityId = 11
                        });
                });

            modelBuilder.Entity("UniversityBookShop.Domain.Entities.PurchasedBookFaculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("FacultyId");

                    b.ToTable("purchased_books_faculty", (string)null);
                });

            modelBuilder.Entity("UniversityBookShop.Domain.Entities.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CurrencyCodesId")
                        .HasColumnType("int")
                        .HasColumnName("currency_code_id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal?>("TotalBookPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("total_book_price");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCodesId");

                    b.ToTable("Universities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrencyCodesId = 1,
                            Description = "A leading institution dedicated to excellence in education and research.",
                            Name = "Starlight University"
                        },
                        new
                        {
                            Id = 2,
                            CurrencyCodesId = 1,
                            Description = "Empowering the future through cutting-edge technology and innovation.",
                            Name = "Galactic Institute of Technology"
                        },
                        new
                        {
                            Id = 3,
                            CurrencyCodesId = 1,
                            Description = "Nurturing creativity and talent in the fields of arts and humanities.",
                            Name = "Celestial Arts Academy"
                        },
                        new
                        {
                            Id = 4,
                            CurrencyCodesId = 1,
                            Description = "Shaping visionary leaders for the global business landscape.",
                            Name = "Stellar Business School"
                        },
                        new
                        {
                            Id = 5,
                            CurrencyCodesId = 1,
                            Description = "Advancing healthcare through research, education, and compassionate practice.",
                            Name = "Lunar Medical University"
                        },
                        new
                        {
                            Id = 6,
                            CurrencyCodesId = 1,
                            Description = "Exploring the mysteries of the cosmos through scientific inquiry.",
                            Name = "Astrological Sciences Institute"
                        },
                        new
                        {
                            Id = 7,
                            CurrencyCodesId = 1,
                            Description = "Fostering environmental stewardship and sustainability for a brighter future.",
                            Name = "Nova Environmental Studies Center"
                        },
                        new
                        {
                            Id = 8,
                            CurrencyCodesId = 1,
                            Description = "Training the next generation of engineers to build a better universe.",
                            Name = "Cosmic Engineering Academy"
                        },
                        new
                        {
                            Id = 9,
                            CurrencyCodesId = 1,
                            Description = "Dedicated to legal excellence and justice in the interstellar community.",
                            Name = "Eclipse Law School"
                        },
                        new
                        {
                            Id = 10,
                            CurrencyCodesId = 1,
                            Description = "Unraveling the mysteries of the cosmos through rigorous scientific study.",
                            Name = "Astronomy and Astrophysics College"
                        },
                        new
                        {
                            Id = 11,
                            CurrencyCodesId = 1,
                            Description = "Understanding society and its dynamics on a global scale for a harmonious future.",
                            Name = "Interplanetary Social Sciences Institute"
                        },
                        new
                        {
                            Id = 12,
                            CurrencyCodesId = 1,
                            Description = "Pushing the boundaries of computing to unlock new frontiers in technology.",
                            Name = "Quantum Computing Research Center"
                        });
                });

            modelBuilder.Entity("UniversityBookShop.Domain.Entities.Book", b =>
                {
                    b.HasOne("UniversityBookShop.Domain.Entities.CurrencyCode", "CurrencyCode")
                        .WithOne("Book")
                        .HasForeignKey("UniversityBookShop.Domain.Entities.Book", "CurrencyCodesId");

                    b.Navigation("CurrencyCode");
                });

            modelBuilder.Entity("UniversityBookShop.Domain.Entities.BooksAvailableForFaculty", b =>
                {
                    b.HasOne("UniversityBookShop.Domain.Entities.Book", "Book")
                        .WithMany("BooksAvailableForFaculty")
                        .HasForeignKey("BookId");

                    b.HasOne("UniversityBookShop.Domain.Entities.Faculty", "Faculty")
                        .WithMany("BooksAvailableForFaculty")
                        .HasForeignKey("FacultyId");

                    b.HasOne("UniversityBookShop.Domain.Entities.University", "University")
                        .WithMany("BooksAvailableForFaculties")
                        .HasForeignKey("UniversityId");

                    b.Navigation("Book");

                    b.Navigation("Faculty");

                    b.Navigation("University");
                });

            modelBuilder.Entity("UniversityBookShop.Domain.Entities.Faculty", b =>
                {
                    b.HasOne("UniversityBookShop.Domain.Entities.University", "University")
                        .WithMany("Faculties")
                        .HasForeignKey("UniversityId");

                    b.Navigation("University");
                });

            modelBuilder.Entity("UniversityBookShop.Domain.Entities.PurchasedBookFaculty", b =>
                {
                    b.HasOne("UniversityBookShop.Domain.Entities.Book", "Book")
                        .WithMany("PurchasedBookFaculty")
                        .HasForeignKey("BookId");

                    b.HasOne("UniversityBookShop.Domain.Entities.Faculty", "Faculty")
                        .WithMany("PurchasedBookFaculty")
                        .HasForeignKey("FacultyId");

                    b.Navigation("Book");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("UniversityBookShop.Domain.Entities.University", b =>
                {
                    b.HasOne("UniversityBookShop.Domain.Entities.CurrencyCode", "CurrencyCode")
                        .WithOne("University")
                        .HasForeignKey("UniversityBookShop.Domain.Entities.University", "CurrencyCodesId");

                    b.Navigation("CurrencyCode");
                });

            modelBuilder.Entity("UniversityBookShop.Domain.Entities.Book", b =>
                {
                    b.Navigation("BooksAvailableForFaculty");

                    b.Navigation("PurchasedBookFaculty");
                });

            modelBuilder.Entity("UniversityBookShop.Domain.Entities.CurrencyCode", b =>
                {
                    b.Navigation("Book");

                    b.Navigation("University");
                });

            modelBuilder.Entity("UniversityBookShop.Domain.Entities.Faculty", b =>
                {
                    b.Navigation("BooksAvailableForFaculty");

                    b.Navigation("PurchasedBookFaculty");
                });

            modelBuilder.Entity("UniversityBookShop.Domain.Entities.University", b =>
                {
                    b.Navigation("BooksAvailableForFaculties");

                    b.Navigation("Faculties");
                });
#pragma warning restore 612, 618
        }
    }
}
