name: CI pipeline .NET and React App

on:
  push:
    branches: ["master", "develop", "CiPiplane"]
  pull_request:
      branches: [ "master", "develop" ]

jobs:
  build_DotNet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
            ./packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}    
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
  test_DotNet:
    runs-on: ubuntu-latest
    needs: build_DotNet
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
            ./packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}          
      - name: Restore dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

