name: Docker Compose with Nginx, react-App, university-book-shop App and MySQL

on:
    push:
      branches: ["master", "develop", "reactApp"]
    pull_request:
        branches: [ "master", "develop" ]

jobs:
  docker-compose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Run Docker Compose
      run: |
        docker-compose up -d